import React, { useState } from 'react';
import {
  PieChart,
  Pie,
  Cell,
  ResponsiveContainer,
  Tooltip,
  Legend,
} from 'recharts';
import {
  Scale,
  Sparkles,
  ShieldCheck,
  Printer,
  ChevronDown,
  ChevronUp,
  Layers,
  ArrowRight,
  ShieldAlert,
  Share2,
  Copy,
  Check,
  Building2,
  Coins,
  TreeDeciduous,
  Globe2,
  Gavel,
  ExternalLink,
  FileText,
  BookOpen,
  Calculator,
} from 'lucide-react';
import { translations } from '../translations/translations';
import { formatPKR, formatPKRWords } from '../utils/inheritanceCalculator';
import FamilyTreeVisualizer from './FamilyTreeVisualizer';
import AssetBreakdownCalculator from './AssetBreakdownCalculator';
import JurisprudenceFaqAssistant from './JurisprudenceFaqAssistant';
import LegalAffidavitModal from './LegalAffidavitModal';

// Curated harmonious color palette for Recharts
const COLORS = [
  '#10b981', // emerald
  '#d4a948', // gold
  '#06b6d4', // cyan
  '#8b5cf6', // violet
  '#f59e0b', // amber
  '#3b82f6', // blue
  '#ec4899', // pink
  '#14b8a6', // teal
  '#6366f1', // indigo
  '#84cc16', // lime
];

export default function ResultsView({
  results,
  formData,
  lang,
  resultsSubTab: controlledSubTab,
  setResultsSubTab: setControlledSubTab,
  onNavigateToPaperwork,
  onPrint,
}) {
  const t = translations[lang];
  const [showAuditTrail, setShowAuditTrail] = useState(false);
  const [localSubTab, setLocalSubTab] = useState('summary'); // 'summary' | 'tree' | 'assets' | 'overseas' | 'faq'
  const [copied, setCopied] = useState(false);
  const [showAffidavit, setShowAffidavit] = useState(false);

  const resultsSubTab = controlledSubTab !== undefined ? controlledSubTab : localSubTab;
  const setResultsSubTab = setControlledSubTab || setLocalSubTab;

  if (!results || !results.heirsList || results.heirsList.length === 0) {
    return (
      <div className="glass-panel p-12 rounded-3xl border border-slate-800 text-center space-y-4">
        <div className="w-16 h-16 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mx-auto text-emerald-400">
          <Scale className="w-8 h-8" />
        </div>
        <h3 className="text-lg font-bold text-slate-200">
          {lang === 'ur' ? 'کوئی شرعی ورثاء درج نہیں کیے گئے' : 'No Surviving Heirs Selected'}
        </h3>
        <p className="text-xs text-slate-400 max-w-md mx-auto">
          {lang === 'ur'
            ? 'برائے مہربانی بائیں جانب کے فارم میں متوفی کے حیات ورثاء کا انتخاب کریں اور "شرعی حصص کا حساب لگائیں" پر کلک کریں۔'
            : 'Please fill in the family structure form with at least one surviving heir to generate the Islamic estate breakdown.'}
        </p>
      </div>
    );
  }

  const {
    netEstate,
    grossEstate,
    status,
    totalHeirsCount,
    heirsList,
    blockedHeirs,
    auditSteps,
  } = results;

  // Prepare data for Recharts Pie Chart
  const chartData = heirsList.map((heir) => ({
    name: lang === 'ur' ? heir.nameUr : heir.nameEn,
    value: Number(heir.percentage),
    pkr: heir.totalPkr,
    fraction: heir.fractionFormatted,
    category: lang === 'ur' ? heir.categoryUr : heir.category,
  }));

  // Generate WhatsApp Share Text
  const handleWhatsAppShare = () => {
    const lines = [
      `*🏛️ WARIS - Islamic Inheritance Distribution Summary*`,
      `*خالص ترکہ (Net Distributable Estate):* ${formatPKR(netEstate)}`,
      `*شرعی نوعیت (Status):* ${status.toUpperCase()}`,
      `---------------------------------`,
      ...heirsList.map(
        (h) =>
          `• *${h.nameEn} (${h.nameUr})*: ${h.fractionFormatted} (${h.percentage}%) → ${formatPKR(h.totalPkr)}`
      ),
      `---------------------------------`,
      `_Calculated via Waris - Islamic Inheritance & Land Navigator (waris-app.vercel.app)_`,
    ];
    const text = encodeURIComponent(lines.join('\n'));
    window.open(`https://api.whatsapp.com/send?text=${text}`, '_blank');
  };

  const handleCopyText = () => {
    const lines = [
      `🏛️ WARIS - Islamic Inheritance Distribution Summary`,
      `Net Distributable Estate: ${formatPKR(netEstate)}`,
      `Calculation Type: ${status.toUpperCase()}`,
      `---------------------------------`,
      ...heirsList.map(
        (h) =>
          `• ${h.nameEn} (${h.nameUr}): ${h.fractionFormatted} (${h.percentage}%) = ${formatPKR(h.totalPkr)}`
      ),
      `---------------------------------`,
      `Generated by Waris App`,
    ];
    navigator.clipboard.writeText(lines.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner with Calculation Status & Major Actions */}
      <div className="glass-panel-emerald p-6 rounded-3xl border border-emerald-500/30 flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-glow">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-emerald-500/20 border border-emerald-400/30 flex items-center justify-center text-emerald-300 shrink-0">
            <Scale className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-xs px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 font-extrabold border border-emerald-400/30">
                {status === 'awl'
                  ? 'عول (Awl)'
                  : status === 'radd'
                  ? 'رد (Radd)'
                  : 'توزیع عصبہ (Residue)'}
              </span>
              <h2 className="text-base font-extrabold text-slate-100">
                {status === 'awl'
                  ? t.statusAwl
                  : status === 'radd'
                  ? t.statusRadd
                  : t.statusNormal}
              </h2>
            </div>
            <p className="text-xs text-slate-300 mt-0.5">
              {status === 'awl'
                ? lang === 'ur'
                  ? 'مقررہ حصص کا مجموعہ 100% سے زیادہ ہونے پر تمام ورثاء کے حصوں میں متناسب کمی کی گئی ہے۔'
                  : 'Sum of fixed shares exceeded 100%; shares proportionally adjusted per classical Hanafi jurisprudence.'
                : status === 'radd'
                ? lang === 'ur'
                  ? 'کوئی عصبہ موجود نہ ہونے پر بچ جانے والا ترکہ دیگر قرآنی حصہ داروں پر رد کے اصول کے تحت تقسیم کیا گیا۔'
                  : 'Surplus returned proportionally to Quranic sharers via Radd.'
                : lang === 'ur'
                ? 'مقررہ حصص کی تقسیم کے بعد باقی ماندہ ترکہ عصبہ ورثاء میں تقسیم کیا گیا۔'
                : 'Residue distributed to eligible agnatic heirs (Asabah).'}
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2 shrink-0 flex-wrap">
          {/* Generate Legal Affidavit Modal Button */}
          <button
            type="button"
            onClick={() => setShowAffidavit(true)}
            className="px-3.5 py-2 rounded-xl bg-gradient-to-r from-gold-500 to-amber-600 hover:from-gold-400 hover:to-amber-500 text-slate-950 font-black text-xs shadow-glow-gold flex items-center gap-1.5 transition"
            title="Generate Official Stamp-Paper Affidavit"
          >
            <FileText className="w-4 h-4" />
            <span>{lang === 'ur' ? 'قانونی بیانِ حلفی تیار کریں' : 'Generate Court Affidavit'}</span>
          </button>

          <button
            type="button"
            onClick={handleWhatsAppShare}
            className="px-3 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-md flex items-center gap-1.5 transition"
            title="Share on WhatsApp"
          >
            <Share2 className="w-3.5 h-3.5" />
            <span>{lang === 'ur' ? 'واٹس ایپ' : 'WhatsApp'}</span>
          </button>

          <button
            type="button"
            onClick={handleCopyText}
            className="px-3 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 text-xs font-bold border border-slate-700 flex items-center gap-1.5 transition"
            title="Copy Summary Text"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? (lang === 'ur' ? 'کاپی ہو گیا!' : 'Copied!') : (lang === 'ur' ? 'کاپی' : 'Copy')}</span>
          </button>

          <button
            type="button"
            onClick={() => setShowAuditTrail(!showAuditTrail)}
            className="px-3 py-2 rounded-xl bg-slate-900/90 hover:bg-slate-800 text-xs font-semibold text-slate-200 border border-slate-700 flex items-center gap-1.5 transition"
          >
            <Layers className="w-3.5 h-3.5 text-gold-400" />
            <span>{t.btnViewAudit}</span>
            {showAuditTrail ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
          </button>
        </div>
      </div>

      {/* Sub-Tabs Navigation */}
      <div className="flex flex-wrap items-center gap-2 p-1.5 rounded-2xl bg-slate-900/90 border border-slate-800">
        <button
          type="button"
          onClick={() => setResultsSubTab('summary')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
            resultsSubTab === 'summary'
              ? 'bg-emerald-600 text-white shadow-md'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <Sparkles className="w-3.5 h-3.5 text-gold-400" />
          <span>{lang === 'ur' ? '1. خلاصہ و چارٹ' : '1. Summary & Donut Chart'}</span>
        </button>

        <button
          type="button"
          onClick={() => setResultsSubTab('tree')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
            resultsSubTab === 'tree'
              ? 'bg-emerald-600 text-white shadow-md'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <TreeDeciduous className="w-3.5 h-3.5 text-emerald-400" />
          <span>{lang === 'ur' ? '2. شجرۂ وراثت (Family Tree)' : '2. Visual Shajra Tree'}</span>
        </button>

        <button
          type="button"
          onClick={() => setResultsSubTab('assets')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
            resultsSubTab === 'assets'
              ? 'bg-emerald-600 text-white shadow-md'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <Calculator className="w-3.5 h-3.5 text-gold-300" />
          <span>{lang === 'ur' ? '3. مکان، اراضی و سونا' : '3. Property & Gold Divider'}</span>
        </button>

        <button
          type="button"
          onClick={() => setResultsSubTab('overseas')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
            resultsSubTab === 'overseas'
              ? 'bg-emerald-600 text-white shadow-md'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <Globe2 className="w-3.5 h-3.5 text-cyan-400" />
          <span>{lang === 'ur' ? '4. بیرونِ ملک ورثاء و دفعہ 498-A' : '4. Overseas Heirs & Legal Rights'}</span>
        </button>

        <button
          type="button"
          onClick={() => setResultsSubTab('faq')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
            resultsSubTab === 'faq'
              ? 'bg-emerald-600 text-white shadow-md'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <BookOpen className="w-3.5 h-3.5 text-emerald-400" />
          <span>{lang === 'ur' ? '5. فقہی و قانونی رہنمائی' : '5. Shariah & Dispute FAQ'}</span>
        </button>
      </div>

      {/* Audit Trail Drawer */}
      {showAuditTrail && (
        <div className="p-6 rounded-3xl bg-slate-900 border border-slate-700/80 shadow-2xl space-y-4 animate-fadeIn">
          <div className="flex items-center gap-2 text-gold-400 font-bold text-xs">
            <Layers className="w-4 h-4" />
            <span>{lang === 'ur' ? 'مرحلہ وار فقہی حساب کتاب (Audit Trail)' : 'Step-by-Step Jurisprudential Audit Trail'}</span>
          </div>
          <p className="text-xs text-slate-300">
            {lang === 'ur'
              ? 'حنفی فقہ کے مطابق ہر مرحلے کا حسابی استدلال اور کسر کی تبدیلی:'
              : 'Detailed deduction logic and fractional adjustments per classical Hanafi jurisprudence:'}
          </p>
          <div className="space-y-2">
            {auditSteps &&
              auditSteps.map((step, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800 text-xs flex items-start gap-3"
                >
                  <span className="w-5 h-5 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold text-[10px] shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <div className="space-y-1">
                    <span className="font-bold text-slate-200">{step.step}</span>
                    <p className="text-slate-400 text-[11px] leading-relaxed">
                      {lang === 'ur' ? step.explanationUr || step.explanation : step.explanation}
                    </p>
                  </div>
                </div>
              ))}
          </div>
        </div>
      )}

      {/* ================= VIEW 1: Summary Table & Donut Chart ================= */}
      {resultsSubTab === 'summary' && (
        <div className="space-y-6">
          {/* Metrics Overview */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="glass-panel p-5 rounded-2xl border border-slate-800">
              <span className="text-xs text-slate-400 font-medium">{t.metricNetEstate}</span>
              <div className="text-xl sm:text-2xl font-black text-emerald-400 mt-1">
                {formatPKR(netEstate)}
              </div>
              <span className="text-[10px] text-slate-500 block truncate mt-0.5">
                {formatPKRWords(netEstate, lang)}
              </span>
            </div>

            <div className="glass-panel p-5 rounded-2xl border border-slate-800">
              <span className="text-xs text-slate-400 font-medium">{t.metricTotalHeirs}</span>
              <div className="text-xl sm:text-2xl font-black text-slate-100 mt-1">
                {totalHeirsCount} {lang === 'ur' ? 'افراد' : 'Individual(s)'}
              </div>
              <span className="text-[10px] text-slate-500 block mt-0.5">
                {heirsList.length} {lang === 'ur' ? 'وارث زمرے' : 'heir group(s)'}
              </span>
            </div>

            <div className="glass-panel p-5 rounded-2xl border border-slate-800">
              <span className="text-xs text-slate-400 font-medium">{t.metricCalculationType}</span>
              <div className="text-base sm:text-lg font-bold text-gold-400 mt-1 uppercase">
                {status}
              </div>
              <span className="text-[10px] text-slate-400 block mt-0.5">
                {status === 'awl'
                  ? 'عول (Proportional Reduction)'
                  : status === 'radd'
                  ? 'رد (Surplus Returned)'
                  : 'معمول کی تقسیم (Residuary)'}
              </span>
            </div>
          </div>

          {/* Chart & Table Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Donut Chart */}
            <div className="lg:col-span-5 glass-panel p-6 rounded-3xl border border-slate-800 flex flex-col items-center justify-center">
              <h3 className="text-xs font-bold text-slate-300 mb-2">{t.chartTitle}</h3>
              <div className="w-full h-64 sm:h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={chartData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={95}
                      paddingAngle={3}
                      dataKey="value"
                    >
                      {chartData.map((entry, index) => (
                        <Cell
                          key={`cell-${index}`}
                          fill={COLORS[index % COLORS.length]}
                          stroke="#0f172a"
                          strokeWidth={2}
                        />
                      ))}
                    </Pie>
                    <Tooltip
                      content={({ active, payload }) => {
                        if (active && payload && payload.length) {
                          const data = payload[0].payload;
                          return (
                            <div className="p-3 bg-slate-900 border border-slate-700 rounded-xl shadow-xl text-xs space-y-1">
                              <span className="font-bold text-slate-200 block">{data.name}</span>
                              <span className="text-emerald-400 block font-bold">
                                {data.fraction} ({data.value}%)
                              </span>
                              <span className="text-gold-400 block font-semibold">
                                {formatPKR(data.pkr)}
                              </span>
                            </div>
                          );
                        }
                        return null;
                      }}
                    />
                    <Legend
                      layout="horizontal"
                      verticalAlign="bottom"
                      align="center"
                      wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Shares Table */}
            <div className="lg:col-span-7 glass-panel p-6 rounded-3xl border border-slate-800 space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-xs font-bold text-slate-300">
                  {lang === 'ur' ? 'ورثاء کی فہرست و تفصیلات:' : 'Heirs Share Breakdown:'}
                </h3>
                <span className="text-[10px] text-slate-500">
                  {lang === 'ur' ? 'کل حصص: 100%' : 'Total Estate: 100%'}
                </span>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs text-slate-300">
                  <thead className="bg-slate-900/90 text-[11px] font-bold text-slate-400 uppercase tracking-wider border-b border-slate-800">
                    <tr>
                      <th className="py-3 px-3">{t.tableColHeir}</th>
                      <th className="py-3 px-2">{t.tableColFraction}</th>
                      <th className="py-3 px-2">{t.tableColPercent}</th>
                      <th className="py-3 px-3">{t.tableColTotalPKR}</th>
                      <th className="py-3 px-3">{t.tableColPerIndividual}</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800/80">
                    {heirsList.map((heir) => (
                      <tr key={heir.id} className="hover:bg-slate-900/40 transition">
                        <td className="py-3 px-3 font-bold text-slate-100">
                          <div>{lang === 'ur' ? heir.nameUr : heir.nameEn}</div>
                          <div className="text-[10px] font-normal text-slate-400">
                            {heir.count} {lang === 'ur' ? 'وارث' : 'individual(s)'}
                          </div>
                        </td>
                        <td className="py-3 px-2 font-bold text-emerald-400 text-sm">
                          {heir.fractionFormatted}
                        </td>
                        <td className="py-3 px-2 font-semibold text-slate-200">
                          {heir.percentage}%
                        </td>
                        <td className="py-3 px-3 font-bold text-gold-400">
                          {formatPKR(heir.totalPkr)}
                        </td>
                        <td className="py-3 px-3 text-slate-300">
                          <div className="font-semibold">{formatPKR(heir.perIndividualPkr)}</div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ================= VIEW 2: Family Tree ================= */}
      {resultsSubTab === 'tree' && (
        <FamilyTreeVisualizer
          formData={formData || { deceasedGender: 'male' }}
          results={results}
          lang={lang}
        />
      )}

      {/* ================= VIEW 3: Physical Asset Divider ================= */}
      {resultsSubTab === 'assets' && (
        <AssetBreakdownCalculator results={results} lang={lang} />
      )}

      {/* ================= VIEW 4: Overseas Heirs & Section 498A ================= */}
      {resultsSubTab === 'overseas' && (
        <div className="space-y-6">
          <div className="p-6 rounded-3xl bg-slate-900 border-2 border-gold-500/30 shadow-glow-gold space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gold-500/20 border border-gold-500/30 flex items-center justify-center text-gold-300">
                <Gavel className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-base font-extrabold text-slate-100">
                  {lang === 'ur'
                    ? 'خواتین کو وراثت سے محروم کرنے پر قانونی سزا (دفعہ 498-A مجموعہ تعزیراتِ پاکستان)'
                    : 'Criminal Liability for Depriving Female Heirs (Section 498A PPC)'}
                </h3>
                <span className="text-xs text-gold-400 font-semibold">
                  {lang === 'ur'
                    ? '10 سال تک قیدِ بامشقت اور 10 لاکھ روپے جرمانہ'
                    : 'Up to 10 Years Rigorous Imprisonment & PKR 1,000,000 Fine'}
                </span>
              </div>
            </div>

            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              {lang === 'ur'
                ? 'پاکستانی قانون (Section 498A of Pakistan Penal Code) کے تحت کسی بھی بیوہ، بیٹی یا بہن کو فریب، دباؤ، حلف نامہ یا زبردستی دستبرداری کے ذریعے جائیداد کے شرعی حق سے محروم کرنا سنگین ناقابلِ ضمانت جرم ہے۔ سپریم کورٹ آف پاکستان کے تاریخی فیصلوں کے مطابق زبانی یا اسٹامپ پیپر پر دستبرداری (Tamleek / Release Deed) اگر زبردستی لی گئی ہو تو باطل تصور ہوتی ہے۔'
                : 'Under Section 498A of the Pakistan Penal Code (PPC), coercing or deceitfully depriving any female heir (wife, daughter, mother, or sister) of her legal inheritance is a non-bailable criminal offense punishable with 5 to 10 years imprisonment. The Supreme Court of Pakistan has consistently ruled that coercive relinquishment or sham compromise deeds are void ab initio.'}
            </p>
          </div>

          <div className="p-6 rounded-3xl bg-slate-900 border border-slate-800 space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-teal-500/20 border border-teal-500/30 flex items-center justify-center text-teal-300">
                <Globe2 className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-base font-extrabold text-slate-100">
                  {lang === 'ur'
                    ? 'بیرونِ ملک مقیم ورثاء (Overseas Pakistanis) کا بائیومیٹرک طریقہ کار'
                    : 'Succession Protocol for Overseas Pakistani Legal Heirs'}
                </h3>
                <span className="text-xs text-teal-400 font-semibold">
                  {lang === 'ur' ? 'نادرا ڈیجیٹل پاور آف اٹارنی اور سفارت خانہ تصدیق' : 'Digital Power of Attorney & Foreign Mission Attestation'}
                </span>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
              <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 space-y-2">
                <h4 className="text-xs font-bold text-slate-100">
                  {lang === 'ur' ? '1. نادرا آن لائن پاور آف اٹارنی پورٹل:' : '1. NADRA Digital Power of Attorney (PoA):'}
                </h4>
                <p className="text-[11px] text-slate-300 leading-relaxed">
                  {lang === 'ur'
                    ? 'اگر کوئی وارث پاکستان میں موجود نہیں ہے، تو وہ نادرا کے پورٹل پر آن لائن بائیومیٹرک اور ویڈیو تصدیق کے ذریعے پاکستان میں موجود اپنے کسی بھی رشتہ دار یا وکیل کو مختار نامہ تفویض کر سکتا ہے۔'
                    : 'Overseas heirs who cannot travel to Pakistan can execute a legal Digital Power of Attorney online via NADRA’s portal with video link interview and digital fingerprint verification.'}
                </p>
                <a
                  href="https://poa.nadra.gov.pk"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1.5 text-xs text-emerald-400 font-bold hover:underline pt-1"
                >
                  <span>poa.nadra.gov.pk</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>
              </div>

              <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 space-y-2">
                <h4 className="text-xs font-bold text-slate-100">
                  {lang === 'ur' ? '2. سفارت خانے میں بائیومیٹرک:' : '2. Embassy / Consulate Biometrics:'}
                </h4>
                <p className="text-[11px] text-slate-300 leading-relaxed">
                  {lang === 'ur'
                    ? 'سکسیشن ایکٹ 2021 کے تحت، بیرونِ ملک پاکستانی کسی بھی قریبی پاکستانی سفارت خانے یا قونصل خانے کے نادرا ڈیسک پر جا کر جانشینی درخواست کے لیے اپنا فنگر پرنٹ بائیومیٹرک درج کروا سکتے ہیں۔'
                    : 'Under the Letters of Administration & Succession Certificates Act 2021, overseas legal heirs can record their formal biometric verification at NADRA desks in Pakistan Embassies / Consulates worldwide.'}
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ================= VIEW 5: Islamic Jurisprudence & Legal FAQ ================= */}
      {resultsSubTab === 'faq' && <JurisprudenceFaqAssistant lang={lang} />}

      {/* Blocked Heirs Notice */}
      {blockedHeirs && blockedHeirs.length > 0 && (
        <div className="p-5 rounded-2xl bg-amber-950/20 border border-amber-500/30 space-y-3">
          <div className="flex items-center gap-2 text-amber-400 font-bold text-xs">
            <ShieldAlert className="w-4 h-4" />
            <span>{t.blockedTitle}</span>
          </div>
          <p className="text-xs text-slate-300">{t.blockedDesc}</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
            {blockedHeirs.map((blocked, i) => (
              <div
                key={i}
                className="p-3 rounded-xl bg-slate-900/90 border border-amber-500/20 text-xs space-y-1"
              >
                <span className="font-bold text-amber-300">
                  {lang === 'ur' ? blocked.nameUr : blocked.nameEn}
                </span>
                <p className="text-[11px] text-slate-400">
                  {lang === 'ur' ? blocked.reasonUr : blocked.reasonEn}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Legal Stamp-Paper Affidavit Generator Modal */}
      <LegalAffidavitModal
        isOpen={showAffidavit}
        onClose={() => setShowAffidavit(false)}
        formData={formData}
        results={results}
        lang={lang}
      />
    </div>
  );
}
